version: 2
jobs:
  test_35:
    docker:
      - image: python:3.5
        environment:
          DOCKER_DIST_DIR: /root/project
          CONFIG_PATH: tests
    steps:
      - checkout
      - run: python setup.py test
  test_37:
    docker:
      - image: python:3.7
        environment:
          DOCKER_DIST_DIR: /root/project
          CONFIG_PATH: tests
    steps:
      - checkout
      - run: python setup.py test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_35
      - test_35
      - build_37
      - test_37
