version: 2
jobs:
  build:
    docker:
      - image: alunir/laurel-build:latest
    steps:
      - checkout
      - run:
          - python setup.py build
  test:
    docker:
      - image: alunir/laurel-build:latest
    steps:
      - checkout
      - run:
          - python setup.py test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
