version: 2
jobs:
  build_35:
    docker:
      - image: python:3.5
    steps:
      - checkout
      - run: python setup.py build
  test_35:
    docker:
      - image: python:3.5
    steps:
      - checkout
      - run: python setup.py test
  build_37:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run: python setup.py build
  test_37:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run: python setup.py test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_35
      - test_35
      - build_37
      - test_37
