version: 2
jobs:
  build:
    docker:
      - image: jimako1989/laurel-build:latest
    steps:
      - checkout
      - run: python setup.py build
  test:
    docker:
      - image: jimako1989/laurel-build:latest
    steps:
      - checkout
      - run: python setup.py test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
